--- #YAML:1.0
name:                Term-Cap
version:             1.11
abstract:            Perl termcap interface
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Test::More:                    0.33
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Jonathan Stowe <gellyfish@gellyfish.com>
